import React, { useState } from 'react';
import {
  SummarizerContainer,
  SummarizerTitle,
  InputTextArea,
  SummarizeButton,
  SummaryOutputContainer,
  SummaryOutputTitle,
  SummaryText,
} from './AISummarizer.styles'; // Assuming you save the styled components in a separate file

function AISummarizer() {
  const [inputText, setInputText] = useState('');
  const [summary, setSummary] = useState('');
  const [isSummarizing, setIsSummarizing] = useState(false); // For potential loading state

  const handleSummarize = () => {
    // In a real application, you would send the inputText to an AI service
    // and update the 'summary' state with the response.
    // For now, let's simulate a summarized text.
    setIsSummarizing(true);
    setTimeout(() => {
      const mockSummary = `This is a mock summary of the text you provided. It condenses the main points into a shorter version. Imagine this was generated by a sophisticated AI model that understands the nuances of language.`;
      setSummary(mockSummary);
      setIsSummarizing(false);
    }, 1500); // Simulate a short delay for processing
  };

  return (
    <SummarizerContainer>
      <SummarizerTitle>Cosmic Condenser: Summarize Your Text</SummarizerTitle>

      <InputTextArea
        placeholder="Paste the text you want to summarize here..."
        value={inputText}
        onChange={(e) => setInputText(e.target.value)}
      />

      <SummarizeButton onClick={handleSummarize} disabled={isSummarizing}>
        {isSummarizing ? 'Summarizing...' : 'Summarize'}
      </SummarizeButton>

      {summary && (
        <SummaryOutputContainer>
          <SummaryOutputTitle>Summary</SummaryOutputTitle>
          <SummaryText>{summary}</SummaryText>
        </SummaryOutputContainer>
      )}
    </SummarizerContainer>
  );
}

export default AISummarizer;